name: Android CI

on:
  push:
    branches:
      - /^(uat|prd)-\d\.\d\.\d$/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle

    - name: Install Android SDK
      uses: android-actions/setup-android@v3
      with:
        sdk-version: '31.0.0' # Use the desired Android SDK version

    - name: Grant execute permission for build script
      run: chmod +x ./build_script.sh

    - name: Build APK
      run: ./build_script.sh

    - name: Upload APK as artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: trendy
        path: trendy.apk
